[package]
name = "test"
version = "0.0.0"
publish = false
edition = "2018"

[[bin]]
name = "empty"
path = "empty.rs"

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
